export enum Category {
  FOOD_AND_DRINK = 1,
  PURCHASES = 2,
  ACCOMMODATION = 3,
  PUBLIC_TRANSPORT = 4,
  PERSONAL_TRANSPORT = 5,
  ENTERTAINMENT = 6,
  COMMUNICATION_AND_INTERNET = 7,
  INVESTMENTS = 8,
  TAX = 9,
  FINES = 10,
  MONEY_TRANSFER = 11,
  MONEY_INCOME = 12
}
